.PHONY: clean All

All:
	@echo "----------Building project:[ MSU - Release ]----------"
	@cd "MSU" && $(MAKE) -f  "MSU.mk"
clean:
	@echo "----------Cleaning project:[ MSU - Release ]----------"
	@cd "MSU" && $(MAKE) -f  "MSU.mk" clean
